---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    # not the best choice, just for simplicity
    tag: 3.6.3-jdk

inputs:
  - name: spring-boot-service

run:
  path: "mvn"
  args:
    - -f
    - spring-boot-service/pom.xml
    - clean
    - package

outputs:
  - name: spring-boot-service-out
    path: spring-boot-service