resource_types:
  - name: kubectl-resource
    type: docker-image
    source:
      repository: jmkarthik/concourse-kubectl-resource
      tag: latest

resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/nsteps/spring-k8s-helm-concource.git
      branch: master

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

  - name: kubectl
    type: kubectl-resource
    source:
      api_server_uri: ((server))
      namespace: ((namespace))
      certificate_authority_data: ((cad))
      token: ((token))

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/.ci/tasks/mvn-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: repository
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/.ci/tasks/mvn-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: repository-out

  - name: deploy
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: false
        passed: [package]

      - put: kubectl
        params:
          file: "spring-boot-service/deploy.yaml"